### ISSUE TITLE
fail to fetch trips data

### ISSUE THREAD

**Issue by Dina-Sharafeldeen** [adonmo/mobilitydb-sqlalchemy-demo#3]
Hello,
First of all, I would like to thank you for this demo.
I was trying the demo https://mobilitydb-sqlalchemy-demo.adonmo.com/
I found the message: Fail to fetch trips data

**Comment by chaitan94** [comment]
Hi @Dina-Sharafeldeen,

Thanks for noticing and reporting the issue. Seems like we had a slight misconfiguration in the deployment of the live demo. I have just fixed the issue. It should be good now. However, do note that the demo can always be run locally in case the live demo fails.
